# Generated by Django 5.1.6 on 2025-03-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('high_school', 'High School')], default='primary', max_length=20),
        ),
    ]
