# Generated by Django 5.1.6 on 2025-03-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_school_school_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_gender_type',
            field=models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('mixed', 'Mixed')], default='mixed', max_length=10),
        ),
    ]
