# Generated by Django 5.1.6 on 2025-03-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_school_school_gender_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='student',
            field=models.ManyToManyField(to='core.student'),
        ),
    ]
