# Generated by Django 5.1.6 on 2025-03-20 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_classroom_student_student_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
