# Generated by Django 5.1.6 on 2025-03-11 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_classroom_student_student_classroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='class_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='school_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='school_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='school_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='classroom',
        ),
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='core.classroom'),
            preserve_default=False,
        ),
    ]
