# Generated by Django 5.1.6 on 2025-03-11 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_class_id_classroom_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='school_gender_type',
            new_name='gender_type',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='school_type',
            new_name='type',
        ),
    ]
